CREATE TABLE `tasks` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INT UNSIGNED NOT NULL,
  `priority` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `address` VARCHAR(255) NOT NULL DEFAULT '',
	`lat` DECIMAL(10, 8) NOT NULL DEFAULT 0.0,
  `lng` DECIMAL(11, 8) NOT NULL DEFAULT 0.0,
	`created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB Default CHARSET=utf8mb4;

CREATE TABLE `users` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(100) NOT NULL,
	`username` VARCHAR(50) NOT NULL,
	`first` VARCHAR(30) NOT NULL,
	`middle` VARCHAR(30) NOT NULL,
	`last` VARCHAR(75) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(15) NOT NULL,
	`address` VARCHAR(255) NOT NULL DEFAULT '',
	`lat` DECIMAL(10, 8) NOT NULL DEFAULT 0.0,
  `lng` DECIMAL(11, 8) NOT NULL DEFAULT 0.0,
	`status` VARCHAR(20) NOT NULL DEFAULT 'active',
	`created_on` DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
) ENGINE=InnoDB AUTO_INCREMENT=500 DEFAULT CHARSET=utf8mb4;

-- fix for mysql8
ALTER USER node IDENTIFIED WITH mysql_native_password BY 'node';
